# Generated by Django 4.2.13 on 2024-06-02 21:04

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_cartorder_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('Cancelled', 'Cancelled'), ('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_review', 'In review'), ('draft', 'Drafted'), ('disabled', 'Disabled'), ('published', 'Published')], default='published', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('3', '3 Star'), ('4', '4 Star'), ('1', '1 Star'), ('2', '2 Star'), ('5', '5 Star')], default=None),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(default='category.jpg', upload_to='products')),
                ('active', models.BooleanField(default=True)),
                ('gid', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=10, max_length=10, prefix='', unique=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
