# Generated by Django 4.2.13 on 2024-06-02 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cartorder_payment_status_alter_product_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=40)),
                ('rate', models.IntegerField(default=5, help_text='Numbers added here are in percentage e.g 5%')),
                ('active', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('Cancelled', 'Cancelled'), ('fulfilled', 'Fulfilled')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('Cancelled', 'Cancelled')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('in_review', 'In review'), ('disabled', 'Disabled'), ('draft', 'Drafted'), ('published', 'Published')], default='published', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('2', '2 Star'), ('4', '4 Star'), ('5', '5 Star'), ('1', '1 Star'), ('3', '3 Star')], default=None),
        ),
    ]
