# Generated by Django 4.2.13 on 2024-06-03 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_tax_alter_cartorder_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tax',
            options={'verbose_name_plural': 'Taxes'},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='service_free',
            new_name='service_fee',
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('Cancelled', 'Cancelled'), ('paid', 'Paid')], default='processing', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Drafted'), ('in_review', 'In review'), ('published', 'Published'), ('disabled', 'Disabled')], default='published', max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[('1', '1 Star'), ('2', '2 Star'), ('4', '4 Star'), ('3', '3 Star'), ('5', '5 Star')], default=None),
        ),
    ]
