# Generated by Django 4.2.13 on 2024-06-04 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmedia',
            name='link',
            field=models.CharField(blank=True, help_text='Social Media link', max_length=100, null=True),
        ),
    ]
