# Generated by Django 5.0.4 on 2024-04-30 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('agent', 'Agent'), ('farmer', 'Farmer')], default='customer', max_length=20),
        ),
    ]
